from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    """Stable application error codes shared across API responses."""

    COMMON_SUCCESS = "COMMON.SUCCESS"
    COMMON_VALIDATION_ERROR = "COMMON.VALIDATION_ERROR"
    COMMON_BUSINESS_ERROR = "COMMON.BUSINESS_ERROR"
    AUTH_CLOUD_IDENTITY_MISSING = "AUTH.CLOUD_IDENTITY_MISSING"
    AGENT_AUTH_USERNAME_TAKEN = "AGENT_AUTH.USERNAME_TAKEN"
    AGENT_AUTH_INVALID_CREDENTIALS = "AGENT_AUTH.INVALID_CREDENTIALS"
    AGENT_AUTH_ACCESS_TOKEN_EXPIRED = "AGENT_AUTH.ACCESS_TOKEN_EXPIRED"
    AGENT_AUTH_REFRESH_TOKEN_EXPIRED = "AGENT_AUTH.REFRESH_TOKEN_EXPIRED"
    AGENT_AUTH_SESSION_REVOKED = "AGENT_AUTH.SESSION_REVOKED"
    AGENT_AUTH_WECHAT_LOGIN_SESSION_EXPIRED = "AGENT_AUTH.WECHAT_LOGIN_SESSION_EXPIRED"
    AGENT_AUTH_WECHAT_LOGIN_SESSION_PENDING = "AGENT_AUTH.WECHAT_LOGIN_SESSION_PENDING"
    AGENT_AUTH_WECHAT_LOGIN_SESSION_CONSUMED = "AGENT_AUTH.WECHAT_LOGIN_SESSION_CONSUMED"
    AGENT_AUTH_WECHAT_IDENTITY_NOT_SUBSCRIBED = "AGENT_AUTH.WECHAT_IDENTITY_NOT_SUBSCRIBED"
    AGENT_AUTH_WECHAT_CALLBACK_INVALID = "AGENT_AUTH.WECHAT_CALLBACK_INVALID"
    AGENT_AUTH_WECHAT_CONFIG_MISSING = "AGENT_AUTH.WECHAT_CONFIG_MISSING"
    AGENT_AUTH_EMAIL_LOGIN_CHALLENGE_EXPIRED = "AGENT_AUTH.EMAIL_LOGIN_CHALLENGE_EXPIRED"
    AGENT_AUTH_EMAIL_LOGIN_CODE_INVALID = "AGENT_AUTH.EMAIL_LOGIN_CODE_INVALID"
    AGENT_AUTH_EMAIL_SEND_COOLDOWN = "AGENT_AUTH.EMAIL_SEND_COOLDOWN"
    AGENT_AUTH_EMAIL_CONFIG_MISSING = "AGENT_AUTH.EMAIL_CONFIG_MISSING"
    AGENT_AUTH_EMAIL_DELIVERY_FAILED = "AGENT_AUTH.EMAIL_DELIVERY_FAILED"
    BUSINESS_CASE_INVALID_DOCUMENT_SET = "BUSINESS_CASE.INVALID_DOCUMENT_SET"
    BUSINESS_CASE_NOT_FOUND = "BUSINESS_CASE.NOT_FOUND"
    MEMBERSHIP_ALREADY_ACTIVE = "MEMBERSHIP.ALREADY_ACTIVE"
    MEMBERSHIP_ORDER_NOT_FOUND = "MEMBERSHIP.ORDER_NOT_FOUND"
    MEMBERSHIP_ORDER_STATUS_INVALID = "MEMBERSHIP.ORDER_STATUS_INVALID"
    MEMBERSHIP_PLAN_NOT_OPEN = "MEMBERSHIP.PLAN_NOT_OPEN"
    PAYMENT_WECHAT_CONFIG_MISSING = "PAYMENT.WECHAT_CONFIG_MISSING"
    CASE_RESEARCH_ORDER_NOT_FOUND = "CASE_RESEARCH.ORDER_NOT_FOUND"
    CASE_RESEARCH_ORDER_STATUS_INVALID = "CASE_RESEARCH.ORDER_STATUS_INVALID"
    PAYMENT_WECHAT_NOTIFY_INVALID = "PAYMENT.WECHAT_NOTIFY_INVALID"
    PAYMENT_WECHAT_NOTIFY_MISMATCH = "PAYMENT.WECHAT_NOTIFY_MISMATCH"
    PAYMENT_WECHAT_ORDER_CREATE_FAILED = "PAYMENT.WECHAT_ORDER_CREATE_FAILED"
    USER_DISABLED = "USER.DISABLED"
    USER_ALREADY_EXISTS = "USER.ALREADY_EXISTS"
    USER_NOT_FOUND = "USER.NOT_FOUND"
    SYSTEM_INTERNAL_ERROR = "SYSTEM.INTERNAL_ERROR"
    SYSTEM_UNEXPECTED_ERROR = "SYSTEM.UNEXPECTED_ERROR"


__all__ = ["ErrorCode"]
