from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    """Stable application error codes shared across API responses."""

    COMMON_SUCCESS = "COMMON.SUCCESS"
    COMMON_VALIDATION_ERROR = "COMMON.VALIDATION_ERROR"
    COMMON_BUSINESS_ERROR = "COMMON.BUSINESS_ERROR"
    AUTH_CLOUD_IDENTITY_MISSING = "AUTH.CLOUD_IDENTITY_MISSING"
    BUSINESS_CASE_INVALID_DOCUMENT_SET = "BUSINESS_CASE.INVALID_DOCUMENT_SET"
    BUSINESS_CASE_NOT_FOUND = "BUSINESS_CASE.NOT_FOUND"
    USER_DISABLED = "USER.DISABLED"
    USER_ALREADY_EXISTS = "USER.ALREADY_EXISTS"
    USER_NOT_FOUND = "USER.NOT_FOUND"
    SYSTEM_INTERNAL_ERROR = "SYSTEM.INTERNAL_ERROR"
    SYSTEM_UNEXPECTED_ERROR = "SYSTEM.UNEXPECTED_ERROR"


__all__ = ["ErrorCode"]
