-- Initialize the current application schema for a fresh PostgreSQL database.
-- Keep this file outside server/api/migrations so the migration runner does
-- not treat the consolidated bootstrap schema as an incremental migration.

BEGIN;

CREATE TABLE IF NOT EXISTS schema_migrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename VARCHAR(255) NOT NULL,
    applied_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_schema_migrations_filename UNIQUE (filename)
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    openid VARCHAR(64) NOT NULL,
    union_id VARCHAR(64) NULL,
    nickname VARCHAR(128) NULL,
    avatar_url VARCHAR(512) NULL,
    status VARCHAR(16) NOT NULL,
    membership_tier VARCHAR(16) NOT NULL DEFAULT 'none',
    membership_started_at TIMESTAMP(6) NULL,
    membership_expires_at TIMESTAMP(6) NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_users_user_id UNIQUE (user_id),
    CONSTRAINT uk_users_openid UNIQUE (openid)
);

CREATE INDEX IF NOT EXISTS idx_users_union_id
    ON users (union_id);
CREATE INDEX IF NOT EXISTS idx_users_membership_tier
    ON users (membership_tier);
CREATE INDEX IF NOT EXISTS idx_users_membership_expires_at
    ON users (membership_expires_at);

CREATE TABLE IF NOT EXISTS business_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id VARCHAR(128) NOT NULL,
    type VARCHAR(16) NOT NULL DEFAULT 'case',
    title VARCHAR(255) NOT NULL,
    summary TEXT NOT NULL,
    summary_markdown TEXT NULL,
    industry VARCHAR(32) NOT NULL DEFAULT '其他',
    data_cutoff_date DATE NULL,
    freshness_months INTEGER NULL,
    tags JSON NOT NULL,
    cover_image_url VARCHAR(2048) NOT NULL,
    status VARCHAR(16) NOT NULL,
    published_at TIMESTAMP(6) NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_business_cases_case_id UNIQUE (case_id)
);

CREATE INDEX IF NOT EXISTS idx_business_cases_status_created_at
    ON business_cases (status, created_at);
CREATE INDEX IF NOT EXISTS idx_business_cases_published_at
    ON business_cases (published_at);
CREATE INDEX IF NOT EXISTS idx_business_cases_public_listing
    ON business_cases (status, type, industry, published_at);

CREATE TABLE IF NOT EXISTS business_case_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    case_id VARCHAR(128) NOT NULL,
    document_type VARCHAR(32) NOT NULL,
    title VARCHAR(255) NOT NULL,
    markdown_content TEXT NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_business_case_documents_document_id UNIQUE (document_id),
    CONSTRAINT uk_business_case_documents_case_document_type UNIQUE (case_id, document_type)
);

CREATE INDEX IF NOT EXISTS idx_business_case_documents_case_id
    ON business_case_documents (case_id);

CREATE TABLE IF NOT EXISTS membership_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    order_no VARCHAR(64) NOT NULL,
    user_id BIGINT NOT NULL,
    openid VARCHAR(64) NOT NULL,
    tier VARCHAR(16) NOT NULL,
    amount_fen INTEGER NOT NULL,
    status VARCHAR(16) NOT NULL,
    prepay_id VARCHAR(128) NULL,
    transaction_id VARCHAR(64) NULL,
    trade_state VARCHAR(32) NULL,
    paid_at TIMESTAMP(6) NULL,
    membership_applied BOOLEAN NOT NULL DEFAULT FALSE,
    membership_started_at TIMESTAMP(6) NULL,
    membership_expires_at TIMESTAMP(6) NULL,
    notify_payload TEXT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_membership_orders_order_id UNIQUE (order_id),
    CONSTRAINT uk_membership_orders_order_no UNIQUE (order_no),
    CONSTRAINT uk_membership_orders_transaction_id UNIQUE (transaction_id)
);

CREATE INDEX IF NOT EXISTS idx_membership_orders_openid
    ON membership_orders (openid);
CREATE INDEX IF NOT EXISTS idx_membership_orders_user_id
    ON membership_orders (user_id);
CREATE INDEX IF NOT EXISTS idx_membership_orders_status
    ON membership_orders (status);
CREATE INDEX IF NOT EXISTS idx_membership_orders_tier
    ON membership_orders (tier);
CREATE INDEX IF NOT EXISTS idx_membership_orders_paid_at
    ON membership_orders (paid_at);

CREATE TABLE IF NOT EXISTS consultation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consultation_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    openid VARCHAR(64) NOT NULL,
    phone VARCHAR(32) NOT NULL,
    email VARCHAR(256) NOT NULL,
    business_type VARCHAR(64) NOT NULL,
    business_type_other VARCHAR(128) NULL,
    business_description TEXT NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_consultation_requests_consultation_id UNIQUE (consultation_id)
);

CREATE INDEX IF NOT EXISTS idx_consultation_requests_user_id
    ON consultation_requests (user_id);
CREATE INDEX IF NOT EXISTS idx_consultation_requests_openid
    ON consultation_requests (openid);
CREATE INDEX IF NOT EXISTS idx_consultation_requests_business_type
    ON consultation_requests (business_type);
CREATE INDEX IF NOT EXISTS idx_consultation_requests_created_at
    ON consultation_requests (created_at);

CREATE TABLE IF NOT EXISTS case_research_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    openid VARCHAR(64) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    visibility VARCHAR(16) NOT NULL DEFAULT 'public',
    status VARCHAR(32) NOT NULL DEFAULT 'pending_review',
    linked_case_id VARCHAR(128) NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_crr_openid_visibility
    ON case_research_requests (openid, visibility, is_deleted);
CREATE INDEX IF NOT EXISTS idx_crr_status
    ON case_research_requests (status);

CREATE TABLE IF NOT EXISTS case_research_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL UNIQUE,
    order_no VARCHAR(64) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    openid VARCHAR(64) NOT NULL,
    amount_fen INTEGER NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'pending',
    prepay_id VARCHAR(128) NULL,
    transaction_id VARCHAR(64) NULL UNIQUE,
    trade_state VARCHAR(32) NULL,
    paid_at TIMESTAMP(6) NULL,
    request_applied BOOLEAN NOT NULL DEFAULT FALSE,
    request_id BIGINT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    notify_payload TEXT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_cro_openid
    ON case_research_orders (openid);
CREATE INDEX IF NOT EXISTS idx_cro_status
    ON case_research_orders (status);

CREATE TABLE IF NOT EXISTS agent_accounts (
    id BIGSERIAL PRIMARY KEY,
    account_id BIGINT NOT NULL UNIQUE,
    username VARCHAR(32) NOT NULL UNIQUE,
    email VARCHAR(256) NULL UNIQUE,
    password_hash VARCHAR(512) NULL,
    password_salt VARCHAR(128) NULL,
    password_scheme_version VARCHAR(16) NULL,
    status VARCHAR(16) NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_agent_accounts_account_id ON agent_accounts (account_id);
CREATE INDEX IF NOT EXISTS idx_agent_accounts_username ON agent_accounts (username);
CREATE INDEX IF NOT EXISTS idx_agent_accounts_email ON agent_accounts (email);

CREATE TABLE IF NOT EXISTS agent_auth_sessions (
    id BIGSERIAL PRIMARY KEY,
    session_id BIGINT NOT NULL UNIQUE,
    account_id BIGINT NOT NULL,
    refresh_token_hash VARCHAR(128) NOT NULL UNIQUE,
    expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITHOUT TIME ZONE NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_agent_auth_sessions_session_id
    ON agent_auth_sessions (session_id);
CREATE INDEX IF NOT EXISTS idx_agent_auth_sessions_account_id
    ON agent_auth_sessions (account_id);
CREATE INDEX IF NOT EXISTS idx_agent_auth_sessions_refresh_token_hash
    ON agent_auth_sessions (refresh_token_hash);

CREATE TABLE IF NOT EXISTS agent_auth_access_tokens (
    id BIGSERIAL PRIMARY KEY,
    token_id BIGINT NOT NULL UNIQUE,
    session_id BIGINT NOT NULL,
    access_token_hash VARCHAR(128) NOT NULL UNIQUE,
    expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_agent_auth_access_tokens_token_id
    ON agent_auth_access_tokens (token_id);
CREATE INDEX IF NOT EXISTS idx_agent_auth_access_tokens_session_id
    ON agent_auth_access_tokens (session_id);
CREATE INDEX IF NOT EXISTS idx_agent_auth_access_tokens_access_token_hash
    ON agent_auth_access_tokens (access_token_hash);

CREATE TABLE IF NOT EXISTS agent_wechat_identities (
    id BIGSERIAL PRIMARY KEY,
    identity_id BIGINT NOT NULL UNIQUE,
    account_id BIGINT NOT NULL,
    official_openid VARCHAR(64) NOT NULL UNIQUE,
    subscribe_status VARCHAR(16) NOT NULL,
    subscribed_at TIMESTAMP WITHOUT TIME ZONE NULL,
    unsubscribed_at TIMESTAMP WITHOUT TIME ZONE NULL,
    last_event_at TIMESTAMP WITHOUT TIME ZONE NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_agent_wechat_identities_identity_id
    ON agent_wechat_identities (identity_id);
CREATE INDEX IF NOT EXISTS idx_agent_wechat_identities_account_id
    ON agent_wechat_identities (account_id);
CREATE INDEX IF NOT EXISTS idx_agent_wechat_identities_official_openid
    ON agent_wechat_identities (official_openid);

CREATE TABLE IF NOT EXISTS agent_wechat_login_sessions (
    id BIGSERIAL PRIMARY KEY,
    login_session_id BIGINT NOT NULL UNIQUE,
    scene_key VARCHAR(128) NOT NULL UNIQUE,
    status VARCHAR(16) NOT NULL,
    official_openid VARCHAR(64) NULL,
    account_id BIGINT NULL,
    login_grant_token_hash VARCHAR(128) NULL UNIQUE,
    expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    authenticated_at TIMESTAMP WITHOUT TIME ZONE NULL,
    consumed_at TIMESTAMP WITHOUT TIME ZONE NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_agent_wechat_login_sessions_login_session_id
    ON agent_wechat_login_sessions (login_session_id);
CREATE INDEX IF NOT EXISTS idx_agent_wechat_login_sessions_scene_key
    ON agent_wechat_login_sessions (scene_key);
CREATE INDEX IF NOT EXISTS idx_agent_wechat_login_sessions_status
    ON agent_wechat_login_sessions (status);

CREATE TABLE IF NOT EXISTS agent_email_login_challenges (
    id BIGSERIAL PRIMARY KEY,
    login_challenge_id BIGINT NOT NULL UNIQUE,
    email VARCHAR(256) NOT NULL,
    code_hash VARCHAR(128) NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    verified_at TIMESTAMP WITHOUT TIME ZONE NULL,
    invalidated_at TIMESTAMP WITHOUT TIME ZONE NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_agent_email_login_challenges_email_created_at
    ON agent_email_login_challenges (email, created_at DESC);

INSERT INTO schema_migrations (filename)
VALUES
    ('0001_create_users.sql'),
    ('0002_create_business_case_tables.sql'),
    ('0003_add_user_profile_fields.sql'),
    ('0004_add_business_case_tags.sql'),
    ('0005_alter_business_case_case_id_to_varchar.sql'),
    ('0006_add_membership_and_orders.sql'),
    ('0007_create_consultation_requests.sql'),
    ('0008_add_business_case_industry.sql'),
    ('0009_drop_business_case_document_cover_image_url.sql'),
    ('0010_add_business_case_type.sql'),
    ('0011_add_business_case_summary_and_freshness_fields.sql'),
    ('0012_create_case_research_tables.sql'),
    ('0013_create_agent_auth_tables.sql'),
    ('0014_add_agent_wechat_login.sql'),
    ('0015_drop_agent_password_fields.sql'),
    ('0016_add_agent_email_login.sql')
ON CONFLICT (filename) DO NOTHING;

COMMIT;
