CREATE TABLE IF NOT EXISTS business_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    summary TEXT NOT NULL,
    cover_image_url VARCHAR(2048) NOT NULL,
    status VARCHAR(16) NOT NULL,
    published_at TIMESTAMP(6) NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_business_cases_case_id UNIQUE (case_id)
);

CREATE INDEX IF NOT EXISTS idx_business_cases_status_created_at
    ON business_cases (status, created_at);
CREATE INDEX IF NOT EXISTS idx_business_cases_published_at
    ON business_cases (published_at);

CREATE TABLE IF NOT EXISTS business_case_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    case_id BIGINT NOT NULL,
    document_type VARCHAR(32) NOT NULL,
    title VARCHAR(255) NOT NULL,
    markdown_content TEXT NOT NULL,
    cover_image_url VARCHAR(2048) NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_business_case_documents_document_id UNIQUE (document_id),
    CONSTRAINT uk_business_case_documents_case_document_type UNIQUE (case_id, document_type)
);

CREATE INDEX IF NOT EXISTS idx_business_case_documents_case_id
    ON business_case_documents (case_id);
