ALTER TABLE users
    ADD COLUMN IF NOT EXISTS membership_tier VARCHAR(16) NOT NULL DEFAULT 'none',
    ADD COLUMN IF NOT EXISTS membership_started_at TIMESTAMP(6) NULL,
    ADD COLUMN IF NOT EXISTS membership_expires_at TIMESTAMP(6) NULL;

CREATE INDEX IF NOT EXISTS idx_users_membership_tier
    ON users (membership_tier);
CREATE INDEX IF NOT EXISTS idx_users_membership_expires_at
    ON users (membership_expires_at);

CREATE TABLE IF NOT EXISTS membership_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    order_no VARCHAR(64) NOT NULL,
    user_id BIGINT NOT NULL,
    openid VARCHAR(64) NOT NULL,
    tier VARCHAR(16) NOT NULL,
    amount_fen INTEGER NOT NULL,
    status VARCHAR(16) NOT NULL,
    prepay_id VARCHAR(128) NULL,
    transaction_id VARCHAR(64) NULL,
    trade_state VARCHAR(32) NULL,
    paid_at TIMESTAMP(6) NULL,
    membership_applied BOOLEAN NOT NULL DEFAULT FALSE,
    membership_started_at TIMESTAMP(6) NULL,
    membership_expires_at TIMESTAMP(6) NULL,
    notify_payload TEXT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_membership_orders_order_id UNIQUE (order_id),
    CONSTRAINT uk_membership_orders_order_no UNIQUE (order_no),
    CONSTRAINT uk_membership_orders_transaction_id UNIQUE (transaction_id)
);

CREATE INDEX IF NOT EXISTS idx_membership_orders_openid
    ON membership_orders (openid);
CREATE INDEX IF NOT EXISTS idx_membership_orders_user_id
    ON membership_orders (user_id);
CREATE INDEX IF NOT EXISTS idx_membership_orders_status
    ON membership_orders (status);
CREATE INDEX IF NOT EXISTS idx_membership_orders_tier
    ON membership_orders (tier);
CREATE INDEX IF NOT EXISTS idx_membership_orders_paid_at
    ON membership_orders (paid_at);
