CREATE TABLE IF NOT EXISTS consultation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consultation_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    openid VARCHAR(64) NOT NULL,
    phone VARCHAR(32) NOT NULL,
    email VARCHAR(256) NOT NULL,
    business_type VARCHAR(64) NOT NULL,
    business_type_other VARCHAR(128) NULL,
    business_description TEXT NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_consultation_requests_consultation_id UNIQUE (consultation_id)
);

CREATE INDEX IF NOT EXISTS idx_consultation_requests_user_id
    ON consultation_requests (user_id);
CREATE INDEX IF NOT EXISTS idx_consultation_requests_openid
    ON consultation_requests (openid);
CREATE INDEX IF NOT EXISTS idx_consultation_requests_business_type
    ON consultation_requests (business_type);
CREATE INDEX IF NOT EXISTS idx_consultation_requests_created_at
    ON consultation_requests (created_at);
