-- Create tables for case research requests and payment orders

CREATE TABLE IF NOT EXISTS case_research_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    openid VARCHAR(64) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    visibility VARCHAR(16) NOT NULL DEFAULT 'public',
    status VARCHAR(32) NOT NULL DEFAULT 'pending_review',
    linked_case_id VARCHAR(128) NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_crr_openid_visibility
    ON case_research_requests (openid, visibility, is_deleted);
CREATE INDEX IF NOT EXISTS idx_crr_status
    ON case_research_requests (status);

CREATE TABLE IF NOT EXISTS case_research_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL UNIQUE,
    order_no VARCHAR(64) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    openid VARCHAR(64) NOT NULL,
    amount_fen INTEGER NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'pending',
    prepay_id VARCHAR(128) NULL,
    transaction_id VARCHAR(64) NULL UNIQUE,
    trade_state VARCHAR(32) NULL,
    paid_at TIMESTAMP(6) NULL,
    request_applied BOOLEAN NOT NULL DEFAULT FALSE,
    request_id BIGINT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    notify_payload TEXT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_cro_openid
    ON case_research_orders (openid);
CREATE INDEX IF NOT EXISTS idx_cro_status
    ON case_research_orders (status);
