-- 博主洞察主表：每个博主一行，存储展示卡片字段 + 完整 HTML 报告 + 结构化摘要 JSON。
-- 由 research-kit 的 publish 工具上传产物，website 公开查询使用。
CREATE TABLE IF NOT EXISTS blogger_insights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(128) NOT NULL,
    platform VARCHAR(32) NOT NULL,
    display_name VARCHAR(128) NOT NULL,
    avatar_url VARCHAR(2048) NULL,
    signature VARCHAR(2048) NULL,
    fans_count BIGINT NULL,
    total_works_count INTEGER NULL,
    industry VARCHAR(32) NULL,
    positioning VARCHAR(512) NULL,
    tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    cover_image_url VARCHAR(2048) NULL,
    report_html TEXT NOT NULL,
    report_summary JSONB NULL,
    source_run_id VARCHAR(64) NULL,
    captured_at TIMESTAMP(6) NULL,
    published_at TIMESTAMP(6) NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'published',
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_blogger_insights_slug UNIQUE (slug)
);

CREATE INDEX IF NOT EXISTS idx_blogger_insights_status_published_at
    ON blogger_insights (status, published_at);
CREATE INDEX IF NOT EXISTS idx_blogger_insights_platform
    ON blogger_insights (platform);
CREATE INDEX IF NOT EXISTS idx_blogger_insights_industry
    ON blogger_insights (industry);

-- 沿用 0018 批量授权策略（按 schema 授权 ALL TABLES IN SCHEMA public 已涵盖新表，
-- 但 PostgreSQL 的 ALL TABLES 仅对历史表生效，新表需要重新授权一次）。
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE blogger_insights TO app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app;
