-- 赛道分析主表：一条赛道一行，存储展示卡片字段 + 多份 HTML 报告 (JSONB) + 关键数字摘要
-- 由 research-kit 的 publish-track 工具上传产物，website 在 /library?type=track 公开查询
CREATE TABLE IF NOT EXISTS track_analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(128) NOT NULL,
    track_keyword VARCHAR(128) NOT NULL,
    region VARCHAR(32) NOT NULL,
    audience VARCHAR(64) NOT NULL,
    industry VARCHAR(64) NULL,
    stance VARCHAR(32) NULL,
    stance_summary VARCHAR(512) NULL,
    cover_image_url VARCHAR(2048) NULL,
    tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    key_numbers JSONB NULL,
    reports JSONB NOT NULL,
    report_order JSONB NOT NULL DEFAULT '[]'::jsonb,
    data_sources_count INTEGER NULL,
    source_run_id VARCHAR(64) NULL,
    captured_at TIMESTAMP(6) NULL,
    published_at TIMESTAMP(6) NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'published',
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_track_analyses_slug UNIQUE (slug)
);

CREATE INDEX IF NOT EXISTS idx_track_analyses_status_published_at
    ON track_analyses (status, published_at);
CREATE INDEX IF NOT EXISTS idx_track_analyses_industry
    ON track_analyses (industry);
CREATE INDEX IF NOT EXISTS idx_track_analyses_stance
    ON track_analyses (stance);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE track_analyses TO app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app;
