"""Application exports for the agent_auth module.

Usage:
- Import DTOs and use cases through this package.

Development rules:
- Keep orchestration logic in use cases.
- Depend on ports instead of concrete infrastructure implementations.
"""

from .dtos import (
    AgentAccountRegistration,
    AgentAccountSummary,
    AgentAuthenticationResult,
    AgentEmailVerificationChallengeCreate,
    AgentEmailVerificationChallengeSummary,
    AgentSessionIssue,
    AgentTokenPair,
    AgentWechatIdentityUpsert,
    AgentWechatLoginGrantIssue,
    AgentWechatLoginSessionCreate,
    AgentWechatLoginSessionStatusResult,
    ChangeAgentUsernameCommand,
    ChangeAgentUsernameResult,
    CreateAgentWechatLoginSessionCommand,
    CreateAgentWechatLoginSessionResult,
    ExchangeAgentWechatLoginCommand,
    GetCurrentAgentAccountQuery,
    GetAgentWechatLoginSessionQuery,
    HandleAgentWechatCallbackCommand,
    LogoutAgentSessionCommand,
    LogoutAgentSessionResult,
    RefreshAgentSessionCommand,
    RequestEmailBindingChallengeCommand,
    RequestEmailBindingChallengeResult,
    VerifyEmailBindingChallengeCommand,
    VerifyEmailBindingChallengeResult,
    normalize_agent_email,
    normalize_agent_username,
    normalize_agent_username_input,
)
from .use_cases import (
    ChangeAgentUsernameUseCase,
    CreateAgentWechatLoginSessionUseCase,
    ExchangeAgentWechatLoginUseCase,
    GetCurrentAgentAccountUseCase,
    GetAgentWechatLoginSessionUseCase,
    HandleAgentWechatCallbackUseCase,
    LogoutAgentSessionUseCase,
    RefreshAgentSessionUseCase,
    RequestEmailBindingChallengeUseCase,
    VerifyEmailBindingChallengeUseCase,
)

__all__ = [
    "AgentAccountRegistration",
    "AgentAccountSummary",
    "AgentAuthenticationResult",
    "AgentEmailVerificationChallengeCreate",
    "AgentEmailVerificationChallengeSummary",
    "AgentSessionIssue",
    "AgentTokenPair",
    "AgentWechatIdentityUpsert",
    "AgentWechatLoginGrantIssue",
    "AgentWechatLoginSessionCreate",
    "AgentWechatLoginSessionStatusResult",
    "ChangeAgentUsernameCommand",
    "ChangeAgentUsernameResult",
    "ChangeAgentUsernameUseCase",
    "CreateAgentWechatLoginSessionCommand",
    "CreateAgentWechatLoginSessionResult",
    "CreateAgentWechatLoginSessionUseCase",
    "ExchangeAgentWechatLoginCommand",
    "ExchangeAgentWechatLoginUseCase",
    "GetCurrentAgentAccountQuery",
    "GetCurrentAgentAccountUseCase",
    "GetAgentWechatLoginSessionQuery",
    "GetAgentWechatLoginSessionUseCase",
    "HandleAgentWechatCallbackCommand",
    "HandleAgentWechatCallbackUseCase",
    "LogoutAgentSessionCommand",
    "LogoutAgentSessionResult",
    "LogoutAgentSessionUseCase",
    "RefreshAgentSessionCommand",
    "RefreshAgentSessionUseCase",
    "RequestEmailBindingChallengeCommand",
    "RequestEmailBindingChallengeResult",
    "RequestEmailBindingChallengeUseCase",
    "VerifyEmailBindingChallengeCommand",
    "VerifyEmailBindingChallengeResult",
    "VerifyEmailBindingChallengeUseCase",
    "normalize_agent_email",
    "normalize_agent_username",
    "normalize_agent_username_input",
]
