import type { ServiceSectionData } from "./types";

export const SERVICES: ServiceSectionData[] = [
  {
    id: "business-consult",
    code: "A",
    tier: "main",
    status: "available",
    eyebrow: "主推 01 · 1V1 业务咨询",
    title: "1V1 业务咨询",
    subtitle: "60 分钟深度连麦，给出专业判断与下一步 TODO",
    price: "¥299 / 60 分钟",
    duration: "3 天内安排",
    fit: [
      "面对具体经营决策，需要一个懂你行业的外部视角",
      "想在投入更大成本前，先确认方向与打法是否走得通",
    ],
    doing: [
      "咨询前问卷：把问题收敛到可讨论的颗粒度",
      "60 分钟连麦：围绕你的真实场景给出专业判断",
      "3 – 5 条结论纪要：可直接落地的下一步 TODO",
    ],
    visual: "violet-orbs",
    imageAlt: "1V1 业务咨询服务示意图",
    accent: "violet",
  },
  {
    id: "case-report",
    code: "B",
    tier: "main",
    status: "available",
    eyebrow: "主推 02 · 案例分析单份",
    title: "案例分析单份",
    subtitle: "指定账号 / 项目 / 赛道，24 小时出结构化报告",
    price: "¥39 / 份",
    duration: "24 小时内交付",
    fit: [
      "想系统拆解某个对标账号或项目，又不想自己从零调研",
      "决策前需要一份结构化的第三方参考底稿",
    ],
    doing: [
      "AI 深度调研 + 人工校准：覆盖背景 / 模式 / 数据 / 启示 / 风险",
      "PDF 与 Markdown 双格式交付，方便阅读与二次引用",
      "含简短答疑：对报告结论可追问一次",
    ],
    visual: "cyan-grid",
    imageAlt: "案例分析服务示意图",
    accent: "cyan",
  },
  {
    id: "ip-website",
    code: "C",
    tier: "main",
    status: "available",
    eyebrow: "主推 03 · IP 官网定制（含上线）",
    title: "IP 官网定制（含上线）",
    subtitle: "软件是品牌的线上门面：定制、上线、并教会你自改",
    price: "¥2999 – ¥4999 / 项目",
    duration: "7 – 10 天",
    fit: [
      "需要一个能代表自己专业度的品牌门面，而不是模板站",
      "希望后续文案、页面自己就能改，不被供应商锁定",
    ],
    doing: [
      "3 – 5 页定制（首页 / 关于 / 服务 / 案例 / 联系）+ 标准组件",
      "上线全流程：域名协助购买（归你）、部署、HTTPS、基础 SEO、访问统计",
      "可选 ICP 备案协助 + 1 次视频教学 + Skill 套件（改文案 / 发新页）",
    ],
    notIncluded: [
      "后端业务系统、电商会员体系",
      "代运营、长期 SEO 优化",
      "长期托管费（域名与部署账号归你）",
    ],
    visual: "pink-waves",
    imageAlt: "IP 官网定制服务示意图",
    accent: "pink",
  },
  {
    id: "knowledge-base",
    code: "H",
    tier: "main",
    status: "wip",
    eyebrow: "主推 04 · 本地知识库 + AI 创作智能体",
    title: "本地知识库 + AI 创作智能体",
    subtitle: "让你拥有自己的内容生产线：私有资料沉淀 → AI 带风格创作",
    price: "¥1599 – ¥2499",
    duration: "2 周",
    fit: [
      "长期在产出内容，希望把零散资料沉淀为可复用的知识资产",
      "用过通用 AI 工具，但总是写不出自己的风格与判断",
    ],
    doing: [
      "两份方法论：知识库沉淀方法论 + 基于知识库的 AI 创作方法论",
      "本地工具链交付 + 1 次视频教学",
      "2 周群答疑 + 1 次 1v1 检视，确保真正跑起来",
    ],
    notIncluded: [
      "云端托管（本地运行，隐私边界写合同）",
      "公开数据互联（内容仅你本地可见）",
    ],
    visual: "mixed-aurora",
    imageAlt: "本地知识库与 AI 创作智能体服务示意图",
    accent: "mixed",
  },
  {
    id: "report-subscription",
    code: "D",
    tier: "aux",
    status: "available",
    eyebrow: "辅助 · 案例报告年费订阅",
    title: "案例报告年费订阅",
    subtitle: "小程序年费会员，每周新增脱敏案例报告",
    price: "¥39 / 年",
    duration: "即开即用",
    fit: [
      "想持续看到新鲜的案例拆解，但不需要每份单独下单",
      "把案例库当做日常决策的参考资料",
    ],
    doing: [
      "小程序内阅读全部历史与新增案例报告",
      "每周新增 1 – 2 份（来自案例分析定制 → 脱敏入库）",
      "案例分析付费客户默认赠送 1 个月试用",
    ],
    visual: "cyan-grid",
    imageAlt: "案例报告订阅示意",
    accent: "cyan",
  },
  {
    id: "content-pack",
    code: "E",
    tier: "aux",
    status: "available",
    eyebrow: "辅助 · 爆款素材包",
    title: "爆款素材包",
    subtitle: "按行业打包的成品素材，买完即用",
    price: "¥49 / 包",
    duration: "即下即发",
    fit: [
      "刚起号，需要一组现成的选题、脚本、封面灵感快速开动",
      "不想每次都从零选题，愿意为被验证过的模板付费",
    ],
    doing: [
      "20 – 30 条钩子 + 5 套脚本 + 10 个封面思路",
      "按行业打包（优先 AI 副业 / 独立开发者等）",
      "不承诺更新频率，卖完一季再看",
    ],
    visual: "violet-orbs",
    imageAlt: "爆款素材包示意",
    accent: "violet",
  },
  {
    id: "skill-annual",
    code: "G",
    tier: "aux",
    status: "wip",
    eyebrow: "辅助 · Skill / 智能体年卡",
    title: "Skill / 智能体年卡",
    subtitle: "本 app 内全解锁年卡，所有付费 Skill 无限次使用",
    price: "¥99 / 年（早鸟）",
    duration: "即买即用",
    fit: [
      "本就是 app 的重度用户，想一次性解锁所有付费 Skill",
      "认可「先用起来再说」，愿意为工具箱付一个低门槛的年费",
    ],
    doing: [
      "已 / 即将上架：低粉高赞选题、小红书挂单文案、本地知识库问答、爆款复盘分析师、一源多发",
      "只上架自己跑通过的 Skill，保证可用",
      "早鸟用户后续更新终身免费",
    ],
    visual: "mono-lines",
    imageAlt: "Skill 年卡示意",
    accent: "violet",
  },
  {
    id: "ip-coaching",
    code: "F",
    tier: "aux",
    status: "scarce",
    eyebrow: "辅助 · IP 运营 3 个月陪跑",
    title: "IP 运营 3 个月陪跑",
    subtitle: "3 个月短周期，全流程陪跑，全平台限 1 – 2 席",
    price: "¥9999 / 3 个月",
    duration: "3 个月",
    fit: [
      "准备认真把个人 IP 当事业做，需要一个全流程的外部合伙人",
      "愿意把过程成果对外公开，换取更深度的陪跑资源",
    ],
    doing: [
      "不定期业务复盘 + 定制工具 + 方法论 + 选题 / 打法指导",
      "覆盖定位 → 生产 → 分发 → 私域 → 变现全链路",
      "过程 SOP 沉淀，合作期结束后仍可持续使用",
    ],
    notIncluded: [
      "不承诺具体粉丝数 / 成交数字，只承诺过程 SOP",
      "需同意对外公开最终成果（不同意的单价上浮 30%）",
    ],
    visual: "pink-waves",
    imageAlt: "IP 运营陪跑示意",
    accent: "pink",
  },
];
