export const keywordsStrings = {
  pageHeading: "爆款素材",
  pageSubheading: "勾选关键词后点击「开始采集」自动驱动浏览器抓取。",
  addButtonLabel: "添加",
  addDialogTitle: "添加关键词",
  editDialogTitle: "编辑关键词",
  placeholderText: "",
  validationEmpty: "关键词不能为空",
  validationDuplicate: "关键词已存在（不区分大小写 / 空白）",
  validationTooLong: "关键词长度不能超过 100 字",
  validationRatioPositive: "粉赞比模式下最小点赞/粉丝比必须大于 0",
  validationAuthorMetricsRequired: "粉丝量/点赞数模式至少需要填写一个阈值",
  validationThresholdPair: "比较方式和数值需要同时填写",
  editTooltip: "编辑",
  deleteTooltip: "删除",
  deleteConfirmTitle: "确认删除关键词",
  deleteConfirmBody: (text: string): string => `确认删除「${text}」吗？`,
  confirmButton: "确认",
  cancelButton: "取消",
  emptyListGuidance: "尚未添加任何关键词。点击右上角「添加」开始。",
  loadErrorTitle: "关键词列表加载失败",
  loadErrorFallback: "请重试；如果问题持续存在，检查日志定位异常数据。",
  startBatchLabel: "开始采集",
  startBatchPendingLabel: "正在启动…",
  stopBatchLabel: "停止整批",
  stopBatchPendingLabel: "停止中…",
  batchBusyTooltip: "已有批次进行中，请先停止整批",
  notReadyTooltipPrefix: "还未就绪：",
  noEnabledTooltip: "请至少打开一条关键词的开关",
  notFoundError: "关键词不存在",
  fieldText: "关键词",
  fieldTargetCap: "目标采集数",
  fieldHealthCap: "最多浏览数",
  fieldFilterMode: "筛选模式",
  fieldRatio: "最小点赞/粉丝比",
  fieldFollowerThreshold: "粉丝量",
  fieldLikeThreshold: "点赞数",
  fieldPublishTimeRange: "发布时间",
  filterModeNone: "不筛选",
  filterModeRatio: "粉赞比",
  filterModeAuthorMetrics: "粉丝量 / 点赞数",
  comparisonGte: "大于等于",
  comparisonLte: "小于等于",
  publishTimeAll: "不限",
  publishTimeDay: "一天内",
  publishTimeWeek: "一周内",
  publishTimeHalfYear: "半年内",
  fieldsHelp: "默认 10 / 500；可按粉赞比或粉丝量/点赞数阈值筛选，发布时间默认不限。",
} as const;
